server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
    max-http-post-size: 10240000
  servlet:
    context-path: /zxkj
  max-http-header-size: 20140000


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3366/db_zxkj?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
    username: root
    password: root
  redis:
    # 宿主机IP
    host: 127.0.0.1
    # 端口号
    port: 6379
    # 数据库设置
    database: 0
    # 密码
    password: ''
    # 连接超时时间 单位 ms（毫秒）
    timeout: 3000ms
    lettuce:
      pool:
        # 连接池最大连接数，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间，负数表示没有限制
        max-wait: -1ms
        # 连接池中的最小空闲连接，默认值也是0
        min-idle: 0
        # 连接池中的最大空闲连接，默认值也是8
        max-idle: 8
      shutdown-timeout: 100ms